# Generated by Django 3.0.6 on 2020-05-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Author')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Author', verbose_name='Author')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
